### PR TITLE
Cleanup plugin related code, remove kinit dependency

### PR DESCRIPTION
**Pull request by alex1701c**

### CODE REVIEW

**Comment by matinlotfali** [comment]
Thanks for all this cleanup!
It looks like `K_PLUGIN_CLASS_WITH_JSON` is not supported in Kubuntu 20.04. Could you use a macro to switch between the old and clean approaches for now (like the rest of the places)?
I will remove related macros when we decide to discontinue support for Kubuntu 20.04.

**Comment by matinlotfali** [comment]
Also, please add your name to the contributions list in the `README.md`

**Comment by alex1701c** [comment]
All set and done.

When you discontinue Kubuntu 22.04 support, please bump the QT_MIN_VERSION and KF5_MIN_VERSION variables in the CMakeLists. For some KDE CMake stuff, the behavior depends on the required version. Also, it is nocer to have Cmake tell you that your KF/Qt version is too old, rather than getting build failueres due to some stuff not existing :)

**Comment by matinlotfali** [comment]
Sure I will. Thanks

**Pull request merged**
