### PR TITLE
Add HDR code to shaders

### PR DESCRIPTION
**Pull request by matinlotfali**

### CODE REVIEW

**Comment by aaronkirschen** [comment]
The windows are darkened for me still with this commit. Plasma 6 on Tumbleweed.

**Comment by aaronkirschen** [comment]
With this small change, the effect loads and HDR is working.
```
Subject: [PATCH] Fix issue with shader install path
---
Index: src/CMakeLists.txt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
--- a/src/CMakeLists.txt	(revision c43b0820908766d298ea52fad85792bf3ce7ea7c)
+++ b/src/CMakeLists.txt	(date 1711839108925)
@@ -20,14 +20,14 @@
             KWin::kwin
             Qt${QT_MAJOR_VERSION}::CorePrivate
     )
-    install(FILES shaders/shapecorners_qt6.frag DESTINATION ${KDE_INSTALL_DATADIR}/kwin/shaders RENAME shaders/shapecorners.frag)
-    install(FILES shaders/shapecorners_qt6_core.frag DESTINATION ${KDE_INSTALL_DATADIR}/kwin/shaders RENAME shaders/shapecorners_core.frag)
+    install(FILES shaders/shapecorners_qt6.frag DESTINATION ${KDE_INSTALL_DATADIR}/kwin/shaders RENAME shapecorners.frag)
+    install(FILES shaders/shapecorners_qt6_core.frag DESTINATION ${KDE_INSTALL_DATADIR}/kwin/shaders RENAME shapecorners_core.frag)
 else()
     target_link_libraries(kwin4_effect_shapecorners
             KWinEffects::kwineffects
             KWinEffects::kwinglutils
     )
-    install(FILES shaders/shapecorners_qt5.frag DESTINATION ${KDE_INSTALL_DATADIR}/kwin/shaders RENAME shaders/shapecorners.frag)
-    install(FILES shaders/shapecorners_qt5_core.frag DESTINATION ${KDE_INSTALL_DATADIR}/kwin/shaders RENAME shaders/shapecorners_core.frag)
+    install(FILES shaders/shapecorners_qt5.frag DESTINATION ${KDE_INSTALL_DATADIR}/kwin/shaders RENAME shapecorners.frag)
+    install(FILES shaders/shapecorners_qt5_core.frag DESTINATION ${KDE_INSTALL_DATADIR}/kwin/shaders RENAME shapecorners_core.frag)
 endif()
 install(FILES shaders/shapecorners.glsl DESTINATION ${KDE_INSTALL_DATADIR}/kwin/shaders)
```

**Comment by KingKrouch** [comment]
So I just tried this branch, and it doesn't seem to resolve the issue for me, at least currently.

**Comment by matinlotfali** [comment]
Thanks @aaronkirschen. I applied the fix.
@KingKrouch Let's try again with the latest commit.

**Comment by KingKrouch** [comment]
> Thanks @aaronkirschen. I applied the fix. @KingKrouch Let's try again with the latest commit.

Just tried the recent commit. It improves the brightness situation by a ton, but I still notice that the brightness is a slight bit lower between the desktop effect being on and off, and I noticed that the text and contents inside of each window look blurry (or filtered) as a result of it being on. Unsure what the cause of the second part could be though.
image
image

**Comment by matinlotfali** [comment]
@KingKrouch may I ask you to try again with the latest edits?

**Comment by KingKrouch** [comment]
> @KingKrouch may I ask you to try again with the latest edits?

The contrast issue seems to have improved (It doesn't seem to darken, at least to my eyes), and even my web browser of choice (Vivaldi) has rounded corners now, but it seems like the color for the border is now black as opposed to the accent color chosen in the Plasma personalization settings (in my case, green).

**Comment by matinlotfali** [comment]
Okay. I fixed the outline issue as well. So I am merging the feature

**Pull request merged**
