### PR TITLE
Restore the effect on Kubuntu 20.04 and Debian 11

### PR DESCRIPTION
**Pull request by matinlotfali**

### CODE REVIEW

**Comment by alex1701c** [comment]
@matinlotfali Your README.md says "Compatiblity with KWin from versions 5.23 to 5.26". Though here you restore compat with KWin 5.18. AFIACS for the 5.23 compat, only the ServiceType key needed to be added back.

I'll leave up to you how your support strategy is :)

**Comment by matinlotfali** [comment]
@alex1701c actually by that line in the readme I meant that I personally contributed to the compatibility for KWin 5.23 to 5.26 on top of the base code of ShapeCorners which was written for KWin 5.18. I honestly don't know the meaning of tags, flags, and many different stuff in the old code. I just play with them so the effect would work on different distros and different versions KWin. But I agree. It is getting more and more dirty and ugly.

**Comment by alex1701c** [comment]
Often third parties just target the latest release of Ubuntu LTS/Debian stable. For compatibility with older distros users could check out the previously released versions.

When ones a KWin version that is 7 releases behind, it seems reasonable to not have the bleeding-edge version of a third party addon. Especially with KWin not having any promises to binary or source code compatibility between versions (unlike KDE Frameworks).

**Comment by matinlotfali** [comment]
I get your point. I will be starting to clean up the old code.

**Pull request merged**
