### PR TITLE
Make outline's opacity independent on window's opacity

### LINKED ISSUE #221: Ability to force outline opacity to 100% regardless of the window opacity
The outline color is affected by window opacity, resulting in an opaque window's outline being darker than a transparent window's outline. If the window has both opaque and transparent regions, there's a very noticeable difference.

Notice how almost every window in this screenshot has a different outline color.
outline

EDIT: Perhaps it would be better if the outline opacity depended on the opacity of the window, instead of the opacity of the pixel where the outline is drawn. An option to force 100% opacity would still be nice though.

### Additional information
KDE-Rounded-Corners: v0.6.5
KDE Plasma: v6.0.4

This problem occurs on X11, Wayland and also when the blur effect is disabled.

### PR DESCRIPTION
**Pull request by matinlotfali**
This is to fix #221

### CODE REVIEW

**Comment by scgm0** [comment]
There are some side effects....
图片

**Comment by matinlotfali** [comment]
@scgm0 can you test #229 and see if it fixes it?

**Comment by scgm0** [comment]
> @scgm0 can you test #229 and see if it fixes it?

Didn't solve the problem, I tried using `vec4 outlineOverlay = vec4(mix(tex.rgb, outlineColor.rgb, outlineColor.a), tex.a);` and found that there is still a very shallow outline, maybe there is something else affecting `tex.a`?
图片

**Comment by matinlotfali** [comment]
Instead of `tex.a > 0.0` in the if condition, can you try `tex.a > 0.1`?

**Comment by scgm0** [comment]
> Instead of `tex.a > 0.0` in the if condition, can you try `tex.a > 0.1`?
It played a role!

**Comment by scgm0** [comment]
> Instead of `tex.a > 0.0` in the if condition, can you try `tex.a > 0.1`?

It played a role!

**Comment by matinlotfali** [comment]
Fantastic. I will merge it.

**Pull request merged**
