### PR TITLE
Add window tiling support

### LINKED ISSUE #104: Hide Rounded corners when window is tiled
It would be nice if this effect could hide rounded corners and made them sharp when tiled, because for now it makes tiled windows ugly and unfinished.

image

thanks for your work!

### PR DESCRIPTION
**Pull request by matinlotfali**
This new feature closes #104

### CODE REVIEW

**Comment by lomenzel** [comment]
will this also disable rounded corners on tiled windows with a gap? because there it would be nice to keep it

**Comment by matinlotfali** [comment]
> will this also disable rounded corners on tiled windows with a gap?

I am new to tiling windows. How would someone tile windows with a gap? Can you show me?

**Comment by matinlotfali** [comment]
It looks like polonium implements its own algorithm and modifications for tiling.

Sadly, my only dependency (KWinEffect library) doesn't provide me with signals to monitor the tiling state. So I had to write my own algorithm to just detect the tiling situation on every window. 

This means with my algorithm, even if you just drag and move your windows in a way that they cover the width or height of the screen, it would be considered a tiled situation.

I don't know how crazy it would be to check if the space between screen edges and windows are the same, it would also be considered a tiled situation...

**Comment by matinlotfali** [comment]
@lomenzel I am assuming that the gap is just one number that is used everywhere (horizontally, vertically, edges of screen, and between windows)?

**Comment by lomenzel** [comment]
Yes

**Comment by lomenzel** [comment]
> This means with my algorithm, even if you just drag and move your windows in a way that they cover the width or height of the screen, it would be considered a tiled situation.

That is perfect. If tiled with gaps the rounded corners are perfect and should stay

**Comment by matinlotfali** [comment]
@lomenzel I implemented the gap calculation but I can't test it. Can you test it for me?

**Comment by lomenzel** [comment]
It works just fine all floating windows have round corners tiled ones not. 😁, Except for the toggle "disable roundness on Tile/maximize" it only affects the maximized but not the tiles ones, they always have no roundness regardless of the setting.

**Comment by matinlotfali** [comment]
I guess I can't run away from installing polonium on my computer to figure out what is hapenning.

**Comment by lomenzel** [comment]
I thought polonium just uses the tiling feature of plasma itself. Pressing meta+t lets you make a layout and then drag the windows while holding shift into the tiling zone. In the meta+t screen you can also set the padding

**Comment by matinlotfali** [comment]
> Pressing meta+t lets you make a layout and then drag the windows while holding shift into the tiling zone

Fantastic! I didn't know that at all. Thanks for teaching me.
I used this to fix my code. Can you try it again?

**Comment by guzman109** [comment]
Does this work? I have the main branch installed but do not see a difference

**Comment by matinlotfali** [comment]
@guzman109 It should work. Post an issue with screenshots and debug logs if it doesn't

**Pull request merged**
