### PR TITLE
Draw my own shadows all over with proper active & inactive configuration

### PR DESCRIPTION
**Pull request by matinlotfali**
In this pull request, I am removing the native shadows and I am drawing my own shadows instead to fix issue #59

### CODE REVIEW

**Comment by developer91234** [comment]
So does that mean it's possible to force shadows on CSD windows? (Obviously one can force them on KDE by forcing server decoration, then adding an exclusion to remove the titlebar. However this process is labor intensive and depends on the decoration having that toggle)

**Comment by developer91234** [comment]
Ask because there are no shadows for VSCode when run with CSD, just an outline. 
But the effect does force its own system-wide shadows on GTK4  CSD apps.

**Comment by matinlotfali** [comment]
@developer91234 No I am injecting my own shader into the window. If the window doesn't already have a shadow, I can't draw my own version.

In KWin terms, if `expandedGeometry` is bigger than `frameGeometry`, I can draw my shadow. But if they are equal, I can't.

**Comment by developer91234** [comment]
oh I see.

**Comment by developer91234** [comment]
Maybe there's some way to force SSD from within the effect, then modify it so that it strips out the titlebar and frame?

**Comment by matinlotfali** [comment]
@developer91234 that would become part of the KDecoration domain and not the KWinEffects.

**Comment by developer91234** [comment]
@matinlotfali I guess one way to do it would be to force server decorations on an app, then use the effect to cut out the titlebar area.

**Pull request merged**
