### PR TITLE
Add second outline

### PR DESCRIPTION
**Pull request by matinlotfali**
Screenshot_20240523_110112

### CODE REVIEW

**Comment by scgm0** [comment]
After turning off `Primary Outline`, `Secondary Outline` will not be displayed either.

**Comment by scgm0** [comment]
> @scgm0 that was expected. I need to make it more apparent in the form by disabling the second outline section.

Hopefully they can both be displayed independently, one for the inner contour and one for the outer contour, with the outer contour not dependent on the inner contour.

**Comment by scgm0** [comment]
A strange bug
图片

**Comment by Akselmo** [comment]
Looks great on my end! 

image

**Comment by scgm0** [comment]
It's great!
image

**Pull request merged**
